name = "Valhelsia 6+"
author = "Tylian + ValhelsiaTeam"
version = "6.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbab904295b11715bdab8ff57392a595ec51b79698a634e500d01b9551b5b2a8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
