name = "Valhelsia 6+"
author = "Tylian + ValhelsiaTeam"
version = "6.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf0d2db86d7b01d59c896225a32ce60ad06b78a7f57581b58e083d06c25e300f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
