name = "Valhelsia 6+"
author = "Tylian + ValhelsiaTeam"
version = "6.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16d622dd6bef4ddfe04591a90ec2875e813fefdc7ff3e7ca52f924b4feea6a6d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
