
[item_pipe]

	[item_pipe.speed]
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		no_upgrade = 20
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		basic = 15
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		improved = 10
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		advanced = 5
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		ultimate = 1

	[item_pipe.amount]
		#The amount of items transferred
		#Range: > 1
		no_upgrade = 4
		#The amount of items transferred
		#Range: > 1
		basic = 8
		#The amount of items transferred
		#Range: > 1
		improved = 16
		#The amount of items transferred
		#Range: > 1
		advanced = 32
		#The amount of items transferred
		#Range: > 1
		ultimate = 64

[fluid_pipe]

	[fluid_pipe.amount]
		#The amount of mB transferred each tick
		#Range: > 1
		no_upgrade = 50
		#The amount of mB transferred each tick
		#Range: > 1
		basic = 100
		#The amount of mB transferred each tick
		#Range: > 1
		improved = 500
		#The amount of mB transferred each tick
		#Range: > 1
		advanced = 2000
		#The amount of mB transferred each tick
		#Range: > 1
		ultimate = 10000

[energy_pipe]

	[energy_pipe.amount]
		#The amount of FE transferred each tick
		#Range: > 1
		no_upgrade = 3200
		#The amount of FE transferred each tick
		#Range: > 1
		basic = 51200
		#The amount of FE transferred each tick
		#Range: > 1
		improved = 409600
		#The amount of FE transferred each tick
		#Range: > 1
		advanced = 3276800
		#The amount of FE transferred each tick
		#Range: > 1
		ultimate = 26214400

[gas_pipe]

	[gas_pipe.amount]
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		no_upgrade = 200
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		basic = 400
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		improved = 2000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		advanced = 8000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		ultimate = 40000

