
["Activate or Disable"]
	#Enable Better Combat compatibility
	bettercombat = true
	#Enable Jade compatibility
	enable_jade = true
	#Enable WTHIT compatibility
	wthit = true
	#Enable Cold Sweat compatibility (render changes)
	cold_sweat = true
	#Enable Iron's Spells 'n Spellbooks compatibility
	irons_spellbooks = true

